version: '3.7'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: health
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: